name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install backend deps
        run: npm install
      - name: Install frontend deps
        run: npm install --prefix frontend
      - name: Run ci-check
        run: npm run ci-check
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: 5050
